install:
  - git submodule update --init --recursive
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc
  - refreshenv
  - rustc -V
  - cargo -V
  - bash ci/install_extra.sh

build: off
test_script:
  - bash ci/script.sh

pull_requests:
  do_not_increment_build_number: true
