name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ ubuntu-latest ]

    steps:

      - uses: actions/checkout@v4
      - name: Install minimal stable with clippy and rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: init
        run: git submodule update --init --recursive

      - name: Test
        run: bash ci/script.sh

    # - name: coveralls
    #   run: bash ci/coveralls.sh
